name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image with timestamp tag
      run: |
        TAG=latest
        echo "TAG=$TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag jd-sign-server:$TAG

    - name: Save Docker image to tarball
      run: |
        docker save -o my-image.tar jd-sign-server:$TAG

    - name: Upload image tarball as artifact
      uses: actions/upload-artifact@v4
      with:
        name: jd-sign-server
        path: jd-sign-server.tar
